
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Jan 13 14:40:44 CET 2013
//----------------------------------------------------

package edu.pjwstk.jps.parser;

/** CUP generated interface containing symbol constants. */
public interface Symbols {
  /* terminals */
  public static final int MINUS = 6;
  public static final int DIVIDE = 8;
  public static final int DOUBLE_LITERAL = 3;
  public static final int MULTIPLY = 7;
  public static final int BOOLEAN_LITERAL = 4;
  public static final int LEFT_ROUND_BRACKET = 9;
  public static final int EOF = 0;
  public static final int PLUS = 5;
  public static final int error = 1;
  public static final int RIGHT_ROUND_BRACKET = 10;
  public static final int INTEGER_LITERAL = 2;
}

